language: python
python:
  - 2.7

env:
    global:
        - # need at least this so travis page will show env column
matrix:
    include:
        - python: 2.7
          env: FULL_DEPS=true
# Setup anaconda
# see: gist.github.com/dan-blanchard/7045057
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

install:
    - bash .travis_install.sh
    - pip install coverage objgraph
script:
    - nosetests --with-coverage --cover-package=minpower

branches:
  only:
    - master
